// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollApp.Data;

#nullable disable

namespace PayrollApp.Migrations
{
    [DbContext(typeof(PayrollContext))]
    [Migration("20230212082748_SumColumns")]
    partial class SumColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContributionRateContributionsModel", b =>
                {
                    b.Property<int>("ContributionRatesId")
                        .HasColumnType("int");

                    b.Property<int>("ContributionsModelsId")
                        .HasColumnType("int");

                    b.HasKey("ContributionRatesId", "ContributionsModelsId");

                    b.HasIndex("ContributionsModelsId");

                    b.ToTable("ContributionRateContributionsModel");
                });

            modelBuilder.Entity("PayrollApp.Areas.CalculationData.Models.Contribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FromPay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Contribution");
                });

            modelBuilder.Entity("PayrollApp.Areas.CalculationData.Models.ContributionRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.ToTable("ContributionRate");
                });

            modelBuilder.Entity("PayrollApp.Areas.CalculationData.Models.ContributionsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContributionsModel");
                });

            modelBuilder.Entity("PayrollApp.Areas.EmploymentData.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Coefficient")
                        .HasColumnType("real");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("date");

                    b.Property<DateTime>("Start")
                        .HasColumnType("date");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("PayrollApp.Areas.EmploymentData.Models.ContractType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContractType");
                });

            modelBuilder.Entity("PayrollApp.Areas.EmploymentData.Models.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Workplace");
                });

            modelBuilder.Entity("PayrollApp.Areas.HoursData.Models.HourType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HourType");
                });

            modelBuilder.Entity("PayrollApp.Areas.HoursData.Models.HourTypeCoefficient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Coefficient")
                        .HasColumnType("real");

                    b.Property<int>("HourTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HourTypeId");

                    b.ToTable("HourTypeCoefficient");
                });

            modelBuilder.Entity("PayrollApp.Areas.HoursData.Models.HoursFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HoursFund");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.ContributionAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<int?>("PayrollId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.HasIndex("PayrollId");

                    b.ToTable("ContributionAmount");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.HourTypeAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("HourTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("LabourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HourTypeId");

                    b.HasIndex("LabourId");

                    b.ToTable("HourTypeAmount");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.Labour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Labour");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CityTaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ContributionsBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<decimal>("DependentsChildrenDeductible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DependentsDeductible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DependentsDisabledFullDeductible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DependentsDisabledPartialDeductible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IncomeTaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LabourCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("LabourId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PersonalDeductible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("LabourId");

                    b.ToTable("Payroll");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.ReimbursementAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PayrollId")
                        .HasColumnType("int");

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayrollId");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("ReimbursementAmount");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.WageParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinWage")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("WageParameters");
                });

            modelBuilder.Entity("PayrollApp.Areas.PersonData.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChildInLine")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependent");
                });

            modelBuilder.Entity("PayrollApp.Areas.PersonData.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("ContributionsModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Disability")
                        .HasColumnType("int");

                    b.Property<bool>("FirstEmployment")
                        .HasColumnType("bit");

                    b.Property<bool>("FirstEmploymentWithCompany")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HRVI")
                        .HasColumnType("bit");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("ProtectedBankId")
                        .HasColumnType("int");

                    b.Property<string>("ProtectedIBAN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ContractId");

                    b.HasIndex("ContributionsModelId");

                    b.HasIndex("ProtectedBankId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("PayrollApp.Areas.ReimbursementsData.Models.Deductibles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Base")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Dependent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DisabledDependentFull")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DisabledDependentPartial")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EighthChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FifthChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FirstChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FourthChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<float>("MultiplicationCoefficient")
                        .HasColumnType("real");

                    b.Property<decimal>("NinthChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PersonalCoefficient")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SecondChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SeventhChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SixthChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ThirdChild")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Deductible");
                });

            modelBuilder.Entity("PayrollApp.Areas.ReimbursementsData.Models.Reimbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reimbursement");
                });

            modelBuilder.Entity("PayrollApp.Areas.ReimbursementsData.Models.ReimbursementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("ReimbursementValue");
                });

            modelBuilder.Entity("PayrollApp.Areas.TaxData.Models.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int?>("TaxModelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UpperBound")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("TaxModelId");

                    b.ToTable("TaxBracket");
                });

            modelBuilder.Entity("PayrollApp.Areas.TaxData.Models.TaxBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TaxBreak");
                });

            modelBuilder.Entity("PayrollApp.Areas.TaxData.Models.TaxModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TaxModel");
                });

            modelBuilder.Entity("PayrollApp.Areas.ThirdParties.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("PayrollApp.Areas.ThirdParties.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOPPD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<float>("TaxRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("PayrollApp.Areas.ThirdParties.Models.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("ContributionRateContributionsModel", b =>
                {
                    b.HasOne("PayrollApp.Areas.CalculationData.Models.ContributionRate", null)
                        .WithMany()
                        .HasForeignKey("ContributionRatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.CalculationData.Models.ContributionsModel", null)
                        .WithMany()
                        .HasForeignKey("ContributionsModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayrollApp.Areas.CalculationData.Models.ContributionRate", b =>
                {
                    b.HasOne("PayrollApp.Areas.CalculationData.Models.Contribution", "Contribution")
                        .WithMany()
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("PayrollApp.Areas.EmploymentData.Models.Contract", b =>
                {
                    b.HasOne("PayrollApp.Areas.EmploymentData.Models.ContractType", "ContractType")
                        .WithMany()
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.EmploymentData.Models.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractType");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("PayrollApp.Areas.HoursData.Models.HourTypeCoefficient", b =>
                {
                    b.HasOne("PayrollApp.Areas.HoursData.Models.HourType", "HourType")
                        .WithMany()
                        .HasForeignKey("HourTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HourType");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.ContributionAmount", b =>
                {
                    b.HasOne("PayrollApp.Areas.CalculationData.Models.Contribution", "Contribution")
                        .WithMany()
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.PayrollData.Models.Payroll", null)
                        .WithMany("ContributionAmounts")
                        .HasForeignKey("PayrollId");

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.HourTypeAmount", b =>
                {
                    b.HasOne("PayrollApp.Areas.HoursData.Models.HourType", "HourType")
                        .WithMany()
                        .HasForeignKey("HourTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.PayrollData.Models.Labour", null)
                        .WithMany("HourTypeAmounts")
                        .HasForeignKey("LabourId");

                    b.Navigation("HourType");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.Labour", b =>
                {
                    b.HasOne("PayrollApp.Areas.PersonData.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.Payroll", b =>
                {
                    b.HasOne("PayrollApp.Areas.PayrollData.Models.Labour", "Labour")
                        .WithMany()
                        .HasForeignKey("LabourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Labour");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.ReimbursementAmount", b =>
                {
                    b.HasOne("PayrollApp.Areas.PayrollData.Models.Payroll", null)
                        .WithMany("ReimbursementAmounts")
                        .HasForeignKey("PayrollId");

                    b.HasOne("PayrollApp.Areas.ReimbursementsData.Models.Reimbursement", "Reimbursement")
                        .WithMany()
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("PayrollApp.Areas.PersonData.Models.Dependent", b =>
                {
                    b.HasOne("PayrollApp.Areas.PersonData.Models.Employee", null)
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("PayrollApp.Areas.PersonData.Models.Employee", b =>
                {
                    b.HasOne("PayrollApp.Areas.ThirdParties.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.EmploymentData.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.CalculationData.Models.ContributionsModel", "ContributionsModel")
                        .WithMany()
                        .HasForeignKey("ContributionsModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollApp.Areas.ThirdParties.Models.Bank", "ProtectedBank")
                        .WithMany()
                        .HasForeignKey("ProtectedBankId");

                    b.Navigation("Bank");

                    b.Navigation("Contract");

                    b.Navigation("ContributionsModel");

                    b.Navigation("ProtectedBank");
                });

            modelBuilder.Entity("PayrollApp.Areas.ReimbursementsData.Models.ReimbursementValue", b =>
                {
                    b.HasOne("PayrollApp.Areas.ReimbursementsData.Models.Reimbursement", "Reimbursement")
                        .WithMany()
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("PayrollApp.Areas.TaxData.Models.TaxBracket", b =>
                {
                    b.HasOne("PayrollApp.Areas.TaxData.Models.TaxModel", null)
                        .WithMany("TaxBrackets")
                        .HasForeignKey("TaxModelId");
                });

            modelBuilder.Entity("PayrollApp.Areas.TaxData.Models.TaxBreak", b =>
                {
                    b.HasOne("PayrollApp.Areas.PersonData.Models.Employee", null)
                        .WithMany("TaxBreaks")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("PayrollApp.Areas.ThirdParties.Models.Bank", b =>
                {
                    b.HasOne("PayrollApp.Areas.ThirdParties.Models.Street", "Street")
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("PayrollApp.Areas.ThirdParties.Models.Street", b =>
                {
                    b.HasOne("PayrollApp.Areas.ThirdParties.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.Labour", b =>
                {
                    b.Navigation("HourTypeAmounts");
                });

            modelBuilder.Entity("PayrollApp.Areas.PayrollData.Models.Payroll", b =>
                {
                    b.Navigation("ContributionAmounts");

                    b.Navigation("ReimbursementAmounts");
                });

            modelBuilder.Entity("PayrollApp.Areas.PersonData.Models.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("TaxBreaks");
                });

            modelBuilder.Entity("PayrollApp.Areas.TaxData.Models.TaxModel", b =>
                {
                    b.Navigation("TaxBrackets");
                });
#pragma warning restore 612, 618
        }
    }
}
